source $HOME/.profile
if [[ -f $HOME/.config/private/zshrc ]];
then
	source $HOME/.config/private/zshrc
fi
setopt no_hup

bindkey -v
bindkey -M vicmd -rp '^['
bindkey -M vicmd 'H' vi-first-non-blank
bindkey -M vicmd 'L' vi-end-of-line
bindkey -M vicmd '^[' undefined-key
bindkey -M viins -rp '^['
bindkey -M viins '^[' vi-cmd-mode
bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

autoload zkbd
[[ ! -f $HOME/.zkbd/$TERM-${DISPLAY:-$VENDOR-$OSTYPE} ]] && zkbd
source $HOME/.zkbd/$TERM-${DISPLAY:-$VENDOR-$OSTYPE}
[[ -n ${key[Backspace]} ]] && bindkey "${key[Backspace]}" backward-delete-char
function zle-line-init zle-keymap-select {
	RPS1="${${KEYMAP/vicmd/-- NORMAL --}/(main|viins)/-- INSERT --}"
	RPS2=$RPS1
	zle reset-prompt
}
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line
zle -N zle-line-init
zle -N zle-keymap-select

umask 22

export PS1="%n@%m:%~$ "
export charset="utf-8"
export LANG="en_US.UTF-8"
export PAGER="less -iRM"


alias lf="ls -FA"
alias ll="ls -lA"
alias su="su -m"
alias x="exit"

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

cat /etc/motd
calendar -f /usr/share/calendar/calendar.freebsd

#SSH-AGENT MAGIC:
if [ `pgrep "ssh-agent"` - -s "~/.ssh-agent-instance" ]; then
	. ~/.ssh-agent-instance
 	echo "ssh-agent instance found"
else
	ssh-agent > ~/.ssh-agent-instance
	. ~/.ssh-agent-instance
	echo "ssh-agent instance started"
fi

# XXX: Needs more testing.
if [ -z "$TMUX" ]; then
	# we're not in a tmux session
	# We logged in via SSH

	# if ssh auth variable is missing
	if [ -z "$SSH_AUTH_SOCK" ]; then
		export SSH_AUTH_SOCK="$HOME/.ssh/.auth_socket"
	fi

	# if socket is available create the new auth session
	if [ ! -S "$SSH_AUTH_SOCK" ]; then
		`ssh-agent -a $SSH_AUTH_SOCK` > /dev/null 2>&1
		echo $SSH_AGENT_PID > $HOME/.ssh/.auth_pid
	fi

	# if agent isn't defined, recreate it from pid file
	if [ -z $SSH_AGENT_PID ]; then
		export SSH_AGENT_PID=`cat $HOME/.ssh/.auth_pid`
	fi

	echo "Now add some SSH keys and start tmux."
fi
